#name: CI/CD Pipeline
#
#on:
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main, master ]
#
#jobs:
#  build_and_test:
#    runs-on: ubuntu-latest
#
#    services:
#      postgres:
#        image: postgres:latest
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_DB: test_db
#        ports:
#          - 5432:5432
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#
#      redis:
#        image: redis:latest
#        ports:
#          - 6379:6379
#        options: >-
#          --health-cmd "redis-cli ping"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.11'
#
#    - name: Install dependencies
#      working-directory: FastApiProject_15
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#
#    - name: Run tests
#      working-directory: FastApiProject_15
#      env:
#        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
#        REDIS_URL: redis://localhost:6379/0
#      run: |
#        pytest test_main.py -v
#
#    - name: Build Docker image
#      working-directory: FastApiProject_15
#      run: docker build -t fastapi-app:latest .